// <auto-generated />
namespace MeetMeUp_Updated.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class meetings_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(meetings_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202012111133446_meetings_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
